### PR TITLE
add patches for stricteffects

### PR DESCRIPTION
**Pull request by ringabout**
ref https://github.com/nim-lang/Nim/pull/19380

I checked locally, combined with https://github.com/HugoGranstrom/cdt/pull/1 it should pass CI.

image

### CODE REVIEW

**Comment by HugoGranstrom** [comment]
Thanks :)

I don't really understand what `strictEffects` is or why only `newtons` would be concerned though, there are multiple procs which looks very similar to it, for example `steepest_decent`?

**Comment by ringabout** [comment]
Here is the documentation of https://nim-lang.github.io/Nim/manual.html#effect-system-effectsof-annotation

Basically, `effectsOf` tracks the effects of callbacks. With `stricteffects`, the effects of callback must be checked.

> why only newtons would be concerned though, there are multiple procs which looks very similar to it, for example steepest_decent?

They should be marked too. I did minimal changes to make Nim CI green.

**Comment by HugoGranstrom** [comment]
Ahhh okay, thanks for the explaination :D

I guess the reason only `newtons` needs this then is that it is the only proc which uses an explicit `raises: [ArithmeticError]`. Some day I should add it to all procs of numericalnim, but that day isn't today :sweat_smile: 

Merging this now and marking a new release so we can see if the Nim CI likes it now

**Comment by ringabout** [comment]
Thank you!

**Pull request merged**
